apiVersion: v1
kind: Service
metadata:
  name: dotnetcoreapp-service
  namespace: nsgate1
spec:
  selector:
    app: dotnetcoreapp-podlabel
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer